version: "3"
services:
  web:
    build: ./app
    command: python app/manage.py runserver 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE=${DATABASE}