# Generated by Django 4.2 on 2023-05-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0.0)),
                ('previous_balance', models.FloatField(default=None)),
                ('transaction_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('due_date', models.DateField(default=None)),
                ('is_salary', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('due_date', models.DateField(default=None)),
                ('is_bill', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackers.balance')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='expense_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.expense'),
        ),
        migrations.AddField(
            model_name='balance',
            name='income_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.income'),
        ),
    ]
