# Generated by Django 4.2 on 2023-05-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='expense_id',
            new_name='expense',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='income_id',
            new_name='income',
        ),
    ]
