# Generated by Django 4.2 on 2023-05-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_rename_name_customer_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackers.customer'),
        ),
        migrations.AddField(
            model_name='income',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackers.customer'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='expense_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trackers.expense'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='income_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trackers.income'),
        ),
    ]
