# Generated by Django 4.2 on 2023-05-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_rename_expense_id_balance_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='income',
        ),
        migrations.AddField(
            model_name='balance',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trackers.customer'),
        ),
        migrations.AddField(
            model_name='balance',
            name='transaction_id',
            field=models.UUIDField(default=None, editable=False),
        ),
    ]
