# Generated by Django 4.2 on 2023-05-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_remove_balance_expense_remove_balance_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='transaction_id',
            new_name='transaction_id_ref',
        ),
    ]
