# Generated by Django 4.2 on 2023-05-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0004_rename_transaction_id_balance_transaction_id_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='transaction_id_ref',
        ),
        migrations.AddField(
            model_name='balance',
            name='transaction_id',
            field=models.UUIDField(default=None, editable=False, unique=True),
        ),
    ]
