# Generated by Django 4.2 on 2023-05-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_remove_balance_transaction_id_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='transaction_id',
            field=models.UUIDField(default=None, unique=True),
        ),
    ]
