# Generated by Django 4.2 on 2023-05-17 02:10

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0006_alter_balance_transaction_id'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='expense',
            trigger=pgtrigger.compiler.Trigger(name='track_history', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id)\n                    VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.expense_id)\n                ', hash='0ba9d81bf89ad42829c278378ad69d7627681bd2', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_history_c8c98', referencing='REFERENCING OLD TABLE AS old_values  NEW TABLE AS new_values ', table='trackers_expense', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='income',
            trigger=pgtrigger.compiler.Trigger(name='track_history', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id)\n                    VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.income_id)\n                ', hash='af479b0778a3c24b0a28befe91b148f7b024a3df', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_history_e4b38', referencing='REFERENCING OLD TABLE AS old_values  NEW TABLE AS new_values ', table='trackers_income', when='AFTER')),
        ),
    ]
