# Generated by Django 4.2 on 2023-05-17 02:13

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0007_expense_track_history_income_track_history'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='expense',
            name='track_history',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='income',
            name='track_history',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='expense',
            trigger=pgtrigger.compiler.Trigger(name='track_history', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id)\n                    VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.expense_id);\n                ', hash='c70849a283a6d214691165418a2747c7db3a115a', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_history_c8c98', referencing='REFERENCING OLD TABLE AS old_values  NEW TABLE AS new_values ', table='trackers_expense', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='income',
            trigger=pgtrigger.compiler.Trigger(name='track_history', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id)\n                    VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.income_id);\n                ', hash='39e85db723080330cffb16c2e38a11a83f893a40', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_history_e4b38', referencing='REFERENCING OLD TABLE AS old_values  NEW TABLE AS new_values ', table='trackers_income', when='AFTER')),
        ),
    ]
