# Generated by Django 4.2 on 2023-05-17 02:15

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0008_remove_expense_track_history_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='expense',
            name='track_history',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='income',
            name='track_history',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='expense',
            trigger=pgtrigger.compiler.Trigger(name='track_history', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO trackers_balance\n                    VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.expense_id);\n                ', hash='ba0eeb75b4af0bbe6e664cd7e791c0cb5e3f654e', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_history_c8c98', referencing='REFERENCING OLD TABLE AS old_values  NEW TABLE AS new_values ', table='trackers_expense', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='income',
            trigger=pgtrigger.compiler.Trigger(name='track_history', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO trackers_balance\n                    VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.income_id);\n                ', hash='6256d18a8d0ab37c0894ac0a2e6e0dda93238c72', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_history_e4b38', referencing='REFERENCING OLD TABLE AS old_values  NEW TABLE AS new_values ', table='trackers_income', when='AFTER')),
        ),
    ]
