# Generated by Django 4.2 on 2023-05-17 02:20

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0009_remove_expense_track_history_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='expense',
            name='track_history',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='income',
            name='track_history',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='expense',
            trigger=pgtrigger.compiler.Trigger(name='track_history', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id)\n                    VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.expense_id);\n                ', hash='4c228ce1751637ee7074474b38a4552779810eb8', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_history_c8c98', table='trackers_expense', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='income',
            trigger=pgtrigger.compiler.Trigger(name='track_history', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id)\n                    VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.income_id;\n                ', hash='ab51f72f03566fa42a54b3532178623fb82708c6', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_history_e4b38', table='trackers_income', when='AFTER')),
        ),
    ]
