# Generated by Django 4.2 on 2023-05-17 02:23

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0011_remove_expense_track_history_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='expense',
            name='track_history',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='income',
            name='track_history',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='expense',
            trigger=pgtrigger.compiler.Trigger(name='track_balance_expense', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id) VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.expense_id);', hash='f9f34ff6ad113ec73f78563d7ccf51f6c6848e42', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_balance_expense_58998', table='trackers_expense', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='income',
            trigger=pgtrigger.compiler.Trigger(name='track_balance_income', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id) VALUES (0.0, 0.0, now(), NEW.customer_id, NEW.income_id;', hash='1d70dc45268b1b0f298b9491480b7951ec4a6bc0', level='STATEMENT', operation='UPDATE', pgid='pgtrigger_track_balance_income_f59ce', table='trackers_income', when='AFTER')),
        ),
    ]
