# Generated by Django 4.2 on 2023-05-17 02:27

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0014_remove_expense_track_balance_expense_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='expense',
            name='track_balance_expense',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='income',
            name='track_balance_income',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='expense',
            trigger=pgtrigger.compiler.Trigger(name='track_balance_expense', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id) VALUES (0.0, 0.0, now(), NEW.customer.id, NEW.expense_id);', hash='9b2a64d8d641eef44dd9c6fdb25d4bfef9fa02fb', level='STATEMENT', operation='INSERT', pgid='pgtrigger_track_balance_expense_58998', table='trackers_expense', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='income',
            trigger=pgtrigger.compiler.Trigger(name='track_balance_income', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO trackers_balance (current_balance, previous_balance, transaction_date, customer_id, transaction_id) VALUES (0.0, 0.0, now(), NEW.customer.id, NEW.income_id;', hash='eb39f221fc290858cb3de8e040caafa8ac2d0971', level='STATEMENT', operation='INSERT', pgid='pgtrigger_track_balance_income_f59ce', table='trackers_income', when='AFTER')),
        ),
    ]
